server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/music?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8



mybatis:
  type-aliases-package: com.javaclimb.domain
  mapper-locations: classpath:mapper/*.xml



